import type { LucideIcon } from 'lucide-react';
import {
  ShieldCheck,
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  File,
  FileText,
  Github,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Menu,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Rocket,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: Rocket,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  github: Github,
  check: Check,
  menu: Menu,
  ShieldCheck,
};
