import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {NavBar} from "../components/Navbar";

const inter = Inter({ subsets: ['latin'] })

//Todo: update the site metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//Todo: Add global providers over here
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar/>
      {children}</body>
    </html>
  )
}
